#!/bin/bash

#
# puppetca-clean-caller -- by Dario Berzano <dario.berzano@gmail.com>
#
# This script invokes puppetca --clean <hostname> taking hostname from a SSH
# environment variable: when invoking this script remotely via SSH, it removes
# the invoker machine from the allowed Puppet hosts.
#
# Since only user puppet (or root) can modify things in Puppet, this script
# requires some configuration in the sudoers file and in the system.
#
# 1. User running this script should be puppetremote:
#
#      adduser -u 5353 -g nobody puppetremote
#
# 2. puppetremote should be allowed to run this command only as user puppet,
#    and the environment variable SSH_CLIENT, set by SSH, should be preserved,
#    so, in visudo:
#
#      Defaults:puppetremote env_keep = "SSH_CLIENT SSH_CONNECTION"
#      puppetremote  ALL = (puppet) NOPASSWD: \
#        /var/lib/puppet/puppetca-clean-caller
#
#    provided that you save this script into /var/lib/puppet (i.e., ~puppet)
#    with permissions belonging to user puppet itself.
#
# 3. The script should be associated to a SSH authorized key for user
#    puppetremote, and should be the only command, so, in ~puppetremote/.ssh/
#    authorized_keys:
#
#      command="sudo -u puppet /var/lib/puppet/puppetca-clean-caller" ssh-dss...
#

# This variable should be defined
if [ "$SSH_CLIENT" == "" ]; then
  echo "No SSH_CLIENT in environment!"
  exit 42
fi

# Get caller's IP address from the SSH variable
export Ip=$(echo $SSH_CLIENT | awk '{ print $1 }')

# Get hostname from the IP address
export Host=$(getent hosts $Ip 2> /dev/null | awk '{ print $2 }')

# Clean up stuff
/usr/sbin/puppetca --clean $Host
exit $?
